title: DUNK
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://nikodunk.com" # the base hostname & protocol for your site, e.g. http://example.com
collections:
  writing:
    output: true
    permalink: /:path
plugins:
  - jekyll-feed
feed:
  posts: false
  collections:
    writing:
      path: "/rss.xml"
